<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		
		<title>CVE-2020-5274 - Vulnerability Data</title>
		
		<link rel="shortcut icon" type="image/png" href="/favicon.ico" />
		<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-175514417-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-175514417-4');
</script>

	</head>
<body>

<h2>Vulnerability Data</h2>
<h1>CVE-2020-5274</h1>
<p>In Symfony before versions 5.0.5 and 4.4.5, some properties of the Exception were not properly escaped when the `ErrorHandler` rendered it stacktrace. In addition, the stacktrace were displayed even in a non-debug configuration. The ErrorHandler now escape alls properties of the exception, and the stacktrace is only display in debug configuration. This issue is patched in symfony/http-foundation versions 4.4.5 and 5.0.5</p>

<dl>
	<dt>Published</dt>
	<dd>2020-03-30</dd>

	<dt>Modified</dt>
	<dd>2020-03-30</dd>
</dl>

<h3>References</h3>
<ul>
	<li><a href="https://github.com/symfony/symfony/security/advisories/GHSA-m884-279h-32v2">CONFIRM:https://github.com/symfony/symfony/security/advisories/GHSA-m884-279h-32v2</a></li>
<li><a href="https://github.com/symfony/symfony/commit/629d21b800a15dc649fb0ae9ed7cd9211e7e45db">MISC:https://github.com/symfony/symfony/commit/629d21b800a15dc649fb0ae9ed7cd9211e7e45db</a></li>
<li><a href="https://github.com/symfony/symfony/commit/cf80224589ac05402d4f72f5ddf80900ec94d5ad">MISC:https://github.com/symfony/symfony/commit/cf80224589ac05402d4f72f5ddf80900ec94d5ad</a></li>
</ul>

<footer>
	<p><a href="https://reconmap.org">Track security vulnerabilities</a> with <strong>Reconmap</strong>.</p>
</footer>


</body>
</html>